///
/// XCAssetExtensions.swift
///
/// Automatically generated by SwiftyIB. **DO NOT EDIT**
///
#if canImport(UIKit)

import UIKit

extension UIImage: IBIdentifierWithTraitsMakeable {
    public static func make(with identifier: AssetImageIdentifier, in bundle: Bundle? = nil, compatableWith traits: UITraitCollection? = nil) -> Self? {
        self.init(named: identifier.name, in: bundle, compatibleWith: traits)
    }
}

extension UIColor: IBIdentifierWithTraitsMakeable {

    public static func make(with identifier: AssetImageIdentifier, in bundle: Bundle? = nil, compatableWith traits: UITraitCollection? = nil) -> Self? {
        self.init(named: identifier.name, in: bundle, compatibleWith: traits)
    }
}

extension NSDataAsset: IBIdentifierMakeable {

    public static func make(with identifier: AssetDataIdentifier, in bundle: Bundle? = nil) -> Self? {
        guard let bundle = bundle else {
            return nil
        }
        return self.init(name: identifier.name, bundle: bundle)
    }
}

#endif
