// AssetImageIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated
import SwiftyIB

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
extension AssetImageIdentifier {
	static var TestImage: AssetImageIdentifier {AssetImageIdentifier(name: "TestImage")}
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
extension AssetColorIdentifier {
	static var TestColor: AssetColorIdentifier {AssetColorIdentifier(name: "TestColor")}
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
extension AssetDataIdentifier {
	static var TestData: AssetDataIdentifier {AssetDataIdentifier(name: "TestData")}
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
extension AssetTextureIdentifier {
	static var TestTexture: AssetTextureIdentifier {AssetTextureIdentifier(name: "TestTexture")}
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
extension AssetCubeTextureIdentifier {
	static var TestCube: AssetCubeTextureIdentifier {AssetCubeTextureIdentifier(name: "TestCube")}
}