// AssetImageIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated 

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
enum AssetImageIdentifier: String {
	case TestImage
	case none
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
enum AssetColorIdentifier: String {
	case TestColor
	case none
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
enum AssetDataIdentifier: String {
	case TestData
	case none
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
enum AssetTextureIdentifier: String {
	case TestTexture
	case none
}

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Asset
enum AssetCubeTextureIdentifier: String {
	case TestCube
	case none
}