///IBTypes.swift
/// Automatically generated by SwiftIB. **DO NOT EDIT**

import UIKit

protocol AnyIBScene: StoryboardIdentifiable, SceneIdentifiable { }

protocol IBScene: AnyIBScene {
    associatedtype ViewControllerType: UIViewController
    init(_viewController: ViewControllerType)
}

protocol SceneContainer {
    associatedtype SceneType: IBScene
    var Scene: SceneType { get }
}

protocol StoryboardIdentifiable {
    static var storyboardIdentifier: StoryboardIdentifier { get }   
    var viewController: UIViewController { get }
}

protocol SceneIdentifiable {
    static var sceneIdentifier: SceneIdentifier { get }
    var viewController: UIViewController { get }
}

protocol SegueIdentifiable {
    var segueIdentifier: SegueIdentifier { get }
    var viewController: UIViewController { get }
}

struct IBSegue: SegueIdentifiable {
    let segueIdentifier: SegueIdentifier
    let viewController: UIViewController
}
        
