///IBTypes.swift
/// Automatically generated by SwiftIB. **DO NOT EDIT**

import UIKit

protocol IBScene: StoryboardIdentifiable, SceneIdentifiable {

}

protocol StoryboardIdentifiable {
    static var storyboardIdentifier: StoryboardIdentifier { get }   
    var viewController: UIViewController { get }
}

protocol SceneIdentifiable {
    static var sceneIdentifier: SceneIdentifier { get }
    var viewController: UIViewController { get }
}

protocol SegueIdentifiable {
    var segueIdentifier: SegueIdentifier { get }
    var viewController: UIViewController { get }
}

struct IBSegue: SegueIdentifiable {
    let segueIdentifier: SegueIdentifier
    let viewController: UIViewController
}
