///IBTypes.swift
/// Automatically generated by SwiftIB. **DO NOT EDIT**

import UIKit

protocol IBScene: StoryboardIdentifiable, SceneIdentifiable {
    static var storyboardIdentifier: StoryboardIdentifier { get }
    static var sceneIdentifier: SceneIdentifier { get }
}

protocol StoryboardIdentifiable {
    static var storyboardIdentifier: StoryboardIdentifier { get }
}

protocol SceneIdentifiable {
    static var sceneIdentifier: SceneIdentifier { get }
}

struct IBSegue {
    let identifier: SegueIdentifier
    let viewController: UIViewController
}
