// NibIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated 

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Nib file
enum NibIdentifier: String {
	case CollectionReusableView
	case CollectionViewCell
	case TableViewCell
	case TableViewHeaderFooterView
	case none
}