// SceneIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated 

/// Automatically generated from SwiftyIB
/// Each case represents a distinct scene from a storyboard
enum SceneIdentifier: String {
	case AssetGroupsCollectionViewController
	case AssetGroupsViewController
	case AssetViewerViewController
	case CollectionVC
	case EmbededVC
	case MainTabBarController
	case MainVCScene
	case PDFAssetViewController
	case SecondMainVCScene
	case SecondVC
	case SplitChildVC
	case SplitNav
	case SplitNavTable
	case SplitVC
	case SplitView
	case TableVC
	case none
}