// SceneIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated 

/// Automatically generated from SwiftyIB
/// Each case represents a distinct scene from a storyboard
enum SceneIdentifier: String {
	case CollectionVC
	case EmbededVC
	case MainVCScene
	case SecondMainVCScene
	case SecondVC
	case SplitChildVC
	case SplitNav
	case SplitNavTable
	case SplitVC
	case TableVC
	case none
}