// SegueIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated 

/// Automatically generated from SwiftyIB
/// Each case represents a segue from a storyboard
enum SegueIdentifier: String {
	case ViewControllerSegue
}