// StoryboardIdentifier.swift
//
// Automatically Generated by SwiftyIB from the available IB files
//
// **DO NOT EDIT**
// 
// Any changes will be overwritten when next generated 

/// Automatically generated from SwiftyIB
/// Each case represents a distinct Storyboard file
enum StoryboardIdentifier: String {
	case LaunchScreen
	case Main
	case SecondMain
	case none
}